[package]
name = "voxelmap"
version = "0.1.0"
authors = ["raffitz <raf.a.m.c.gon@gmail.com>"]
edition = "2018"
description = "Converts mathematical descriptions of objects to voxel maps"

[dependencies]
clap = "2.33"
