[package]
name = "voxelmap"
version = "0.4.2"
authors = ["raffitz <raf.a.m.c.gon@gmail.com>"]
edition = "2018"
description = "Creates voxel maps to build voxelised objects"

[dependencies]
clap = "2.33"
logos = "0.12"
pomelo = "0.1.5"
lodepng = "3.4"
rgb = "0.8"
named-binary-tag = "0.6"
